"""Collect every phase C score into results/phaseC/all_scores.md.

Two sections per dataset:
  - the 24-run grid (grid_<ds>_<mode>_<hn|nohn>_lr<LR>, clean splits): cheap dev MRecall@100 at
    every saved step, marked with what happened to that step's checkpoint, and full-corpus
    dev/test MRecall@100 / Recall@100 of the evaluated steps;
  - earlier phase C runs (phaseC_<ds>_*, ref_*), as before.
Every dev score is labelled with the dev set it was computed on, read from the "Data path" line
of its eval_metrics.txt, since earlier runs used the phase A dev sets and the grid the clean ones.
"""
import glob, os, re

R = "results/phaseC"
LOG = f"{R}/phaseC.log"
DEV_SETS = {"qampari_dev500": "dev500", "ambigqa_dev300": "dev300",
            "qampari_cleandev500": "clean dev500", "ambigqa_cleandev500": "clean dev500"}
GRID = re.compile(r"^grid_(qampari|ambigqa)_(single|multi)_(hn|nohn)_lr([0-9.e-]+)$")


def read(f):
    try:
        return open(f).read()
    except OSError:
        return ""


def mrecall(f):
    m = re.search(r"MRecall: ([\d.]+) \| Recall: ([\d.]+)", read(f))  # first block = top-100
    return (float(m.group(1)), float(m.group(2))) if m else None


def dev_set(f):
    m = re.search(r"Data path: \S*/([^/\s]+)\.jsonl", read(f))
    return DEV_SETS.get(m.group(1), m.group(1)) if m else "?"


def fmt(v):
    return f"{v[0]:.2f} / {v[1]:.2f}" if v else "pending"


def lr_key(lr):
    try:
        return float(lr)
    except ValueError:
        return float("inf")


def pruned_steps():
    """{run: {step, ...}} from the driver's 'pruned step' log lines (KEEP_TOP pruning)."""
    out = {}
    for m in re.finditer(r"\] \[(\S+)\] pruned step (\d+)", read(LOG)):
        out.setdefault(m.group(1), set()).add(int(m.group(2)))
    return out


def queued_tags(ds):
    """Tags listed in the full-eval queue (first field of each line), plus any evaluated dir."""
    tags = {l.split()[0] for l in read(f"{R}/full_queue_{ds}.txt").splitlines() if l.split() and l.split()[0] != "END"}
    return tags | {os.path.basename(d) for d in glob.glob(f"{R}/full/{ds}/*")}


QUEUED = {ds: queued_tags(ds) for ds in ("qampari", "ambigqa")}


def step_status(ds, run, s, pruned):
    if f"{run}_s{s}" in QUEUED[ds]:
        return "F"
    if s in pruned.get(run, ()):
        return "P"
    if os.path.isdir(f"checkpoints/{ds}/{run}/checkpoint/step-{s}"):
        return "K"
    return "D"


def old_loader(name):
    if name.startswith("ref_"):
        return "reference"
    return "fixed + hard neg." if "fixhn" in name else ("fixed" if "_fix" in name else "pre-fix")


pruned = pruned_steps()
out = ["# Phase C scores", "",
       "Generated by `training/inf_retriever/tools/phaseC_collect_scores.py`. "
       "Cheap dev = reduced-corpus dev MRecall@100 (biased toward base-like retrieval and hard-negative "
       "training; compare within a mode only). Full = full-corpus MRecall@100 / Recall@100. "
       "The dev set of each score is shown: the grid uses the clean dev sets (500 each, "
       "`data_creation/build_clean_splits.py`); earlier runs used the phase A dev500 / dev300.", ""]

for ds in ("qampari", "ambigqa"):
    out += [f"## {ds.upper()}", ""]

    # ---- 24-run grid ------------------------------------------------------------------------
    runs = []
    for d in glob.glob(f"{R}/grid_{ds}_*"):
        m = GRID.match(os.path.basename(d))
        if m and os.path.isdir(d):
            runs.append((m.group(2), m.group(3), m.group(4), os.path.basename(d)))
    runs.sort(key=lambda r: (r[0], r[1], lr_key(r[2])))
    steps = sorted({int(s[4:]) for *_, n in runs for s in os.listdir(f"{R}/{n}")
                    if s.startswith("step") and s[4:].isdigit()})
    devs = sorted({dev_set(f"{R}/{n}/step{s}/eval_metrics.txt") for *_, n in runs for s in steps
                   if mrecall(f"{R}/{n}/step{s}/eval_metrics.txt")})
    out += ["### Grid: cheap dev MRecall@100 by step", "",
            f"Dev set: {', '.join(devs) or '?'}. Checkpoint of each step: **F** = full-corpus eval "
            "(queued or done), **K** = kept, not full-evaluated, **P** = pruned by `KEEP_TOP` (QAMPARI "
            "keeps the top 3 by cheap dev), **D** = deleted afterwards (AmbigQA: steps not queued for "
            "full eval, removed 2026-09-28 to free disk).", "",
            "| Mode | Data | LR | " + " | ".join(f"step {s}" for s in steps) + " |",
            "| --- | --- | --- | " + " | ".join("---" for _ in steps) + " |"]
    for mode, data, lr, n in runs:
        cells = []
        for s in steps:
            v = mrecall(f"{R}/{n}/step{s}/eval_metrics.txt")
            cells.append(f"{v[0]:.2f} {step_status(ds, n, s, pruned)}" if v else "")
        out.append(f"| {mode} | {data} | {lr} | " + " | ".join(cells) + " |")

    out += ["", "### Grid: full corpus", "",
            "| Mode | Data | LR | Step | Dev set | Dev MRecall / Recall | Test MRecall / Recall |",
            "| --- | --- | --- | --- | --- | --- | --- |"]
    rows = []
    for tag in QUEUED[ds]:
        if not tag.startswith(f"grid_{ds}_") or "_s" not in tag:
            continue
        d = f"{R}/full/{ds}/{tag}"
        n, s = tag.rsplit("_s", 1)
        m = GRID.match(n)
        if not m or not s.isdigit():
            continue
        dv, tv = mrecall(f"{d}/dev/eval_metrics.txt"), mrecall(f"{d}/test/eval_metrics.txt")
        dset = dev_set(f"{d}/dev/eval_metrics.txt") if dv else "–"
        key = (m.group(2), m.group(3), lr_key(m.group(4)), int(s))
        rows.append((key, f"| {m.group(2)} | {m.group(3)} | {m.group(4)} | {s} | {dset} | {fmt(dv)} | {fmt(tv)} |"))
    out += [r for _, r in sorted(rows)] + [""]

    # ---- earlier phase C runs ---------------------------------------------------------------
    old = sorted(d for d in glob.glob(f"{R}/phaseC_{ds}_*") if os.path.isdir(d))
    if old:
        steps = sorted({int(s[4:]) for d in old for s in os.listdir(d)
                        if s.startswith("step") and s[4:].isdigit()})
        out += ["### Earlier runs: cheap dev MRecall@100 by step", "",
                "\"pre-fix\" = trained before the loader fix (QAMPARI golds leak the label through "
                "whitespace; AmbigQA data has no leak). Trained on the pre-audit splits.", "",
                "| Run | Mode | Loader | LR | Dev set | " + " | ".join(f"step {s}" for s in steps) + " |",
                "| --- | --- | --- | --- | --- | " + " | ".join("---" for _ in steps) + " |"]
        for d in old:
            n = os.path.basename(d)
            mode = "multi" if "_multi_" in n else "single"
            lr = n.rsplit("_lr", 1)[1] if "_lr" in n else "?"
            vals = {s: mrecall(f"{d}/step{s}/eval_metrics.txt") for s in steps}
            dsets = {dev_set(f"{d}/step{s}/eval_metrics.txt") for s in steps if vals[s]}
            cells = [f"{vals[s][0]:.2f}" if vals[s] else "" for s in steps]
            out.append(f"| `{n.replace('phaseC_' + ds + '_', '')}` | {mode} | {old_loader(n)} | {lr} | "
                       f"{', '.join(sorted(dsets)) or '–'} | " + " | ".join(cells) + " |")
        out.append("")

    rows = []
    for d in sorted(glob.glob(f"{R}/full/{ds}/*")):
        n = os.path.basename(d)
        if n.startswith("grid_"):
            continue
        dv, tv = mrecall(f"{d}/dev/eval_metrics.txt"), mrecall(f"{d}/test/eval_metrics.txt")
        if not (dv or tv):
            continue
        mode = "single" if "single" in n else "multi"
        dset = dev_set(f"{d}/dev/eval_metrics.txt") if dv else "–"
        rows.append((-(tv[0] if tv else -1), f"| `{n}` | {mode} | {old_loader(n)} | {dset} | {fmt(dv)} | {fmt(tv)} |"))
    if rows:
        note = (" AmbigQA test scores here are contaminated: these runs trained on pre-audit splits that "
                "contain 65 test questions (audit D1)." if ds == "ambigqa" else "")
        out += ["### Earlier runs: full corpus", "",
                "Pre-audit splits." + note, "",
                "| Checkpoint | Mode | Loader | Dev set | Dev MRecall / Recall | Test MRecall / Recall |",
                "| --- | --- | --- | --- | --- | --- |"]
        out += [r for _, r in sorted(rows)] + [""]

open(f"{R}/all_scores.md", "w").write("\n".join(out) + "\n")
print("\n".join(out))
