results_dir="results/gaussian_diverse_mlps_multi_query_inf"

python test.py \
--model_paths ${results_dir}/large_mlps_gaussian_multi_query_full_finetuning_SS_contrastive_all_labels_ordered_lr5e-5_temp0.05_batch512_ep1000_warmup0.05/ ${results_dir}/large_mlps_gaussian_multi_query_full_finetuning_SS_hungarian_contrastive_lr5e-5_temp0.05_batch512_ep1000_warmup0.05/ ${results_dir}/large_mlps_gaussian_multi_query_full_finetuning_SS_contrastive_first_label_lr5e-5_temp0.05_batch512_ep1000_warmup0.05/ ${results_dir}/large_mlps_gaussian_multi_query_full_finetuning_SS_mse_all_labels_lr5e-5_temp0.05_batch512_ep1000_warmup0.05/  --checkpoint_name best_model -n 1 5  --split test --k_values 10 20 50 100 500 --model_type EmbeddingModel --embedding_model_dim 1024 -d data_creation/gaussian/data/diverse_mlps_multi_query_large/ --full_finetuning 


python test.py \
--model_paths ${results_dir}/mlps_gaussian_multi_query_full_finetuning_SS_hungarian_contrastive_lr5e-5_temp0.05_batch512_ep2000_warmup0.05/ ${results_dir}/mlps_gaussian_multi_query_full_finetuning_SS_contrastive_all_labels_ordered_lr5e-5_temp0.05_batch512_ep2000_warmup0.05/ ${results_dir}/mlps_gaussian_multi_query_full_finetuning_SS_contrastive_first_label_lr5e-5_temp0.05_batch512_ep2000_warmup0.05/ ${results_dir}/mlps_gaussian_multi_query_full_finetuning_SS_mse_all_labels_lr5e-5_temp0.05_batch512_ep2000_warmup0.05/  --checkpoint_name best_model -n 1 5  --split train --k_values 10 20 50 100 500 --model_type EmbeddingModel --embedding_model_dim 1024 -d data_creation/gaussian/data/diverse_mlps_multi_query/ --full_finetuning 


# python test.py  --model_paths results/gaussian_diverse_mlps_ood_inf/large_mlps_gaussian_ood_full_finetuning_SS_hungarian_contrastive_lr5e-5_temp0.05_batch512_ep500_warmup0.05/ results/gaussian_diverse_mlps_ood_inf/large_mlps_gaussian_ood_full_finetuning_SS_contrastive_all_labels_ordered_lr5e-5_temp0.05_batch512_ep500_warmup0.05/ results/gaussian_diverse_mlps_ood_inf/large_mlps_gaussian_ood_full_finetuning_SS_contrastive_first_label_lr5e-5_temp0.05_batch512_ep500_warmup0.05/ results/gaussian_diverse_mlps_ood_inf/large_mlps_gaussian_ood_full_finetuning_SS_mse_all_labels_lr5e-5_temp0.05_batch512_ep500_warmup0.05/  --checkpoint_name best_model -n 1 5  --split test --k_values 10 20 50 100 500 --model_type EmbeddingModel --embedding_model_dim 1024 -d data_creation/gaussian/data/diverse_mlps_ood_large/ --full_finetuning